/**
 * F054: Handoff Service — writes task files and live transcript for Claude Code /loop
 *
 * Two outputs:
 * 1. Task files (~/tandem-tasks/task-{timestamp}.md) — created by @code tag in AI panel
 * 2. Live transcript ({projectDir}/.tandem/live-transcript.md) — updated every 10s during recording
 */

import { invoke } from '@tauri-apps/api/core';
import { Transcript, ScreenshotData } from '@/types';
import { ContextBasketItem } from '@/contexts/ContextBasketContext';

// ─── Constants ──────────────────────────────────────────────────────────────

/** How many seconds of transcript to include in @code task files */
export const HANDOFF_TRANSCRIPT_WINDOW_SECS = 300; // 5 minutes

/** Rolling window for live transcript file */
export const LIVE_TRANSCRIPT_WINDOW_SECS = 1800; // 30 minutes

/** Debounce interval for live transcript writes */
export const LIVE_TRANSCRIPT_DEBOUNCE_MS = 10_000; // 10 seconds

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatSecs(secs: number): string {
  const m = Math.floor(secs / 60);
  const s = Math.floor(secs % 60);
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

function formatTimestamp(secs: number): string {
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  const s = Math.floor(secs % 60);
  if (h > 0) return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

/**
 * Filter transcripts to a rolling window ending at the latest segment.
 * If no segments have audio_start_time, returns all transcripts.
 */
export function getRecentTranscripts(
  transcripts: Transcript[],
  windowSecs: number,
): Transcript[] {
  if (transcripts.length === 0) return [];
  const latestTime = transcripts[transcripts.length - 1].audio_start_time;
  if (latestTime == null) return transcripts;
  const cutoff = latestTime - windowSecs;
  return transcripts.filter(t => (t.audio_start_time ?? 0) >= cutoff);
}

// ─── Task Handoff File (@code) ──────────────────────────────────────────────

export interface TaskHandoffData {
  taskDescription: string;
  meetingTitle: string;
  meetingId: string;
  transcripts: Transcript[];
  contextItems: ContextBasketItem[];
  timestamp: Date;
}

export function generateTaskMarkdown(data: TaskHandoffData): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Task: ${data.taskDescription.slice(0, 80)}`);
  lines.push(`Meeting: ${data.meetingTitle} | ${data.timestamp.toLocaleString()}`);
  lines.push('');

  // Instructions
  lines.push('## Instructions');
  lines.push(data.taskDescription);
  lines.push('');

  // Recent transcript
  if (data.transcripts.length > 0) {
    lines.push(`## Recent Transcript (last ${Math.round(HANDOFF_TRANSCRIPT_WINDOW_SECS / 60)} min)`);
    for (const t of data.transcripts) {
      if (!t.text.trim()) continue;
      const ts = t.audio_start_time != null ? `[${formatTimestamp(t.audio_start_time)}]` : `[${t.timestamp}]`;
      lines.push(`${ts} ${t.text.trim()}`);
    }
    lines.push('');
  }

  // Context items (basket)
  const contentItems = data.contextItems.filter(item => item.fullContent.trim());
  if (contentItems.length > 0) {
    lines.push('## Context Items');
    for (const item of contentItems) {
      lines.push(`### ${item.type}: ${item.label}`);
      lines.push(item.fullContent);
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push(`*Generated by Tandem · ${data.timestamp.toISOString()}*`);

  return lines.join('\n');
}

/**
 * Write a task handoff file to {projectDir}/.tandem/tasks/task-{timestamp}.md
 * Returns the written file path.
 */
export async function writeTaskHandoff(projectDir: string, data: TaskHandoffData): Promise<string> {
  const sep = projectDir.includes('\\') ? '\\' : '/';
  const tasksDir = `${projectDir}${sep}.tandem${sep}tasks`;
  const filename = `task-${Date.now()}.md`;
  const filePath = `${tasksDir}${sep}${filename}`;
  const content = generateTaskMarkdown(data);

  await invoke('save_transcript', { filePath, content });
  return filePath;
}

// ─── Tandem CLAUDE.md (written once per project dir) ────────────────────────

const TANDEM_CLAUDE_MD = `# Tandem Integration

This project has Tandem meeting integration. During meetings, Tandem writes files here:

## Task Files (\`.tandem/tasks/*.md\`)
When the user says \`@code <task>\` during a meeting, Tandem creates a task file.
Each file contains the task description, recent transcript context, and any attached items.

**To process:**
1. Read the task file
2. Execute it against this codebase
3. Move the file to \`.tandem/tasks/done/\` (do NOT delete — avoids permission prompts)
4. Write a brief result summary to \`.tandem/response.md\` so Tandem can display it

## Live Transcript (\`.tandem/live-transcript.md\`)
Updated every 10 seconds during recording with a rolling 30-minute window.
Scan for lines containing \`@code\` or \`Tandem,\` that were added since your last check.
If you find a new spoken request, act on it and write a result to \`.tandem/response.md\`.

**Track your position:** Record the last timestamp or line count you processed to avoid duplicates.

## Response File (\`.tandem/response.md\`)
After completing any task, write a short (1-3 sentence) summary here.
Tandem polls this file every 10 seconds and shows your response in the AI panel.
**Clear the file after writing** by writing an empty string, or Tandem will clear it after reading.

## Quick Start
Run this in Claude Code to start polling:
\`\`\`
/loop 1m Check .tandem/tasks/ for new .md files. If found, read the task, execute it, move the file to .tandem/tasks/done/, then write a brief result to .tandem/response.md. Also scan .tandem/live-transcript.md for new lines containing "@code" or "Tandem," since last check. Track what you have already processed.
\`\`\`
`;

/**
 * Write .tandem/CLAUDE.md with integration instructions for Claude Code.
 * Called when the project directory is configured. Safe to overwrite (static content).
 */
export async function ensureTandemClaudeMd(projectDir: string): Promise<void> {
  const sep = projectDir.includes('\\') ? '\\' : '/';
  const filePath = `${projectDir}${sep}.tandem${sep}CLAUDE.md`;
  await invoke('save_transcript', { filePath, content: TANDEM_CLAUDE_MD });
}

// ─── Live Screenshots File ──────────────────────────────────────────────────

export function generateLiveScreenshotsMarkdown(screenshots: ScreenshotData[]): string {
  const lines: string[] = [];

  lines.push('# Live Screenshots');
  lines.push(`Updated: ${new Date().toISOString()}`);
  lines.push('');

  if (screenshots.length === 0) {
    lines.push('*(No screenshots captured yet)*');
    return lines.join('\n');
  }

  for (const ss of screenshots) {
    const ts = ss.recording_elapsed_secs != null
      ? `[${formatTimestamp(ss.recording_elapsed_secs)}]`
      : `[${ss.timestamp}]`;
    lines.push(`## ${ts} ${ss.capture_mode === 'region' ? 'Region' : 'Fullscreen'} — ${ss.width}×${ss.height}`);
    lines.push(`File: ${ss.file_path}`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Write screenshots index to {projectDir}/.tandem/screenshots.md
 */
export async function writeLiveScreenshots(
  projectDir: string,
  screenshots: ScreenshotData[],
): Promise<void> {
  if (screenshots.length === 0) return;
  const sep = projectDir.includes('\\') ? '\\' : '/';
  const filePath = `${projectDir}${sep}.tandem${sep}screenshots.md`;
  const content = generateLiveScreenshotsMarkdown(screenshots);
  await invoke('save_transcript', { filePath, content });
}

// ─── Live Transcript File ───────────────────────────────────────────────────

export function generateLiveTranscriptMarkdown(
  transcripts: Transcript[],
  meetingTitle: string,
): string {
  const lines: string[] = [];

  lines.push(`# Live Transcript — ${meetingTitle}`);
  lines.push(`Updated: ${new Date().toISOString()}`);
  lines.push('');

  for (const t of transcripts) {
    if (!t.text.trim()) continue;
    const ts = t.audio_start_time != null ? `[${formatTimestamp(t.audio_start_time)}]` : `[${t.timestamp}]`;
    lines.push(`${ts} ${t.text.trim()}`);
  }

  if (transcripts.length === 0) {
    lines.push('*(No transcript segments yet)*');
  }

  return lines.join('\n');
}

/**
 * Write the live transcript to {projectDir}/.tandem/live-transcript.md
 */
export async function writeLiveTranscript(
  projectDir: string,
  transcripts: Transcript[],
  meetingTitle: string,
): Promise<void> {
  const sep = projectDir.includes('\\') ? '\\' : '/';
  const filePath = `${projectDir}${sep}.tandem${sep}live-transcript.md`;
  const content = generateLiveTranscriptMarkdown(transcripts, meetingTitle);

  await invoke('save_transcript', { filePath, content });
}