/**
 * F054: Handoff Service — writes task files and live transcript for Claude Code /loop
 *
 * Two outputs:
 * 1. Task files (~/tandem-tasks/task-{timestamp}.md) — created by @code tag in AI panel
 * 2. Live transcript ({projectDir}/.tandem/live-transcript.md) — updated every 10s during recording
 */

import { invoke } from '@tauri-apps/api/core';
import { Transcript } from '@/types';
import { ContextBasketItem } from '@/contexts/ContextBasketContext';

// ─── Constants ──────────────────────────────────────────────────────────────

/** How many seconds of transcript to include in @code task files */
export const HANDOFF_TRANSCRIPT_WINDOW_SECS = 300; // 5 minutes

/** Rolling window for live transcript file */
export const LIVE_TRANSCRIPT_WINDOW_SECS = 1800; // 30 minutes

/** Debounce interval for live transcript writes */
export const LIVE_TRANSCRIPT_DEBOUNCE_MS = 10_000; // 10 seconds

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatSecs(secs: number): string {
  const m = Math.floor(secs / 60);
  const s = Math.floor(secs % 60);
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

function formatTimestamp(secs: number): string {
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  const s = Math.floor(secs % 60);
  if (h > 0) return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
}

/**
 * Filter transcripts to a rolling window ending at the latest segment.
 * If no segments have audio_start_time, returns all transcripts.
 */
export function getRecentTranscripts(
  transcripts: Transcript[],
  windowSecs: number,
): Transcript[] {
  if (transcripts.length === 0) return [];
  const latestTime = transcripts[transcripts.length - 1].audio_start_time;
  if (latestTime == null) return transcripts;
  const cutoff = latestTime - windowSecs;
  return transcripts.filter(t => (t.audio_start_time ?? 0) >= cutoff);
}

// ─── Task Handoff File (@code) ──────────────────────────────────────────────

export interface TaskHandoffData {
  taskDescription: string;
  meetingTitle: string;
  meetingId: string;
  transcripts: Transcript[];
  contextItems: ContextBasketItem[];
  timestamp: Date;
}

export function generateTaskMarkdown(data: TaskHandoffData): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Task: ${data.taskDescription.slice(0, 80)}`);
  lines.push(`Meeting: ${data.meetingTitle} | ${data.timestamp.toLocaleString()}`);
  lines.push('');

  // Instructions
  lines.push('## Instructions');
  lines.push(data.taskDescription);
  lines.push('');

  // Recent transcript
  if (data.transcripts.length > 0) {
    lines.push(`## Recent Transcript (last ${Math.round(HANDOFF_TRANSCRIPT_WINDOW_SECS / 60)} min)`);
    for (const t of data.transcripts) {
      if (!t.text.trim()) continue;
      const ts = t.audio_start_time != null ? `[${formatTimestamp(t.audio_start_time)}]` : `[${t.timestamp}]`;
      lines.push(`${ts} ${t.text.trim()}`);
    }
    lines.push('');
  }

  // Context items (basket)
  const contentItems = data.contextItems.filter(item => item.fullContent.trim());
  if (contentItems.length > 0) {
    lines.push('## Context Items');
    for (const item of contentItems) {
      lines.push(`### ${item.type}: ${item.label}`);
      lines.push(item.fullContent);
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push(`*Generated by Tandem · ${data.timestamp.toISOString()}*`);

  return lines.join('\n');
}

/**
 * Write a task handoff file to {projectDir}/.tandem/tasks/task-{timestamp}.md
 * Returns the written file path.
 */
export async function writeTaskHandoff(projectDir: string, data: TaskHandoffData): Promise<string> {
  const sep = projectDir.includes('\\') ? '\\' : '/';
  const tasksDir = `${projectDir}${sep}.tandem${sep}tasks`;
  const filename = `task-${Date.now()}.md`;
  const filePath = `${tasksDir}${sep}${filename}`;
  const content = generateTaskMarkdown(data);

  await invoke('save_transcript', { filePath, content });
  return filePath;
}

// ─── Tandem CLAUDE.md (written once per project dir) ────────────────────────

const TANDEM_CLAUDE_MD = `# Tandem Integration

This project has Tandem meeting integration. During meetings, Tandem writes files here:

## Task Files (\`.tandem/tasks/*.md\`)
When the user says \`@code <task>\` during a meeting, Tandem creates a task file.
Each file contains the task description, recent transcript context, and any attached items.

**To process:** Read the task, execute it against this codebase, then delete the file.

## Live Transcript (\`.tandem/live-transcript.md\`)
Updated every 10 seconds during recording with a rolling 30-minute window.
Look for spoken requests like "Tandem, start working on..." or "Claude Code, handle..."

**To monitor:** Check for new requests, read surrounding context, and act on them.
Track what you've already processed to avoid duplicates.

## Quick Start
Run this in Claude Code to start polling:
\`\`\`
/loop 1m Check .tandem/tasks/ for new .md files. If found, read the task, execute it, then delete the file. Also check .tandem/live-transcript.md for spoken requests directed at you. Track what you've already processed.
\`\`\`
`;

/**
 * Write .tandem/CLAUDE.md with integration instructions for Claude Code.
 * Called when the project directory is configured. Safe to overwrite (static content).
 */
export async function ensureTandemClaudeMd(projectDir: string): Promise<void> {
  const sep = projectDir.includes('\\') ? '\\' : '/';
  const filePath = `${projectDir}${sep}.tandem${sep}CLAUDE.md`;
  await invoke('save_transcript', { filePath, content: TANDEM_CLAUDE_MD });
}

// ─── Live Transcript File ───────────────────────────────────────────────────

export function generateLiveTranscriptMarkdown(
  transcripts: Transcript[],
  meetingTitle: string,
): string {
  const lines: string[] = [];

  lines.push(`# Live Transcript — ${meetingTitle}`);
  lines.push(`Updated: ${new Date().toISOString()}`);
  lines.push('');

  for (const t of transcripts) {
    if (!t.text.trim()) continue;
    const ts = t.audio_start_time != null ? `[${formatTimestamp(t.audio_start_time)}]` : `[${t.timestamp}]`;
    lines.push(`${ts} ${t.text.trim()}`);
  }

  if (transcripts.length === 0) {
    lines.push('*(No transcript segments yet)*');
  }

  return lines.join('\n');
}

/**
 * Write the live transcript to {projectDir}/.tandem/live-transcript.md
 */
export async function writeLiveTranscript(
  projectDir: string,
  transcripts: Transcript[],
  meetingTitle: string,
): Promise<void> {
  const sep = projectDir.includes('\\') ? '\\' : '/';
  const filePath = `${projectDir}${sep}.tandem${sep}live-transcript.md`;
  const content = generateLiveTranscriptMarkdown(transcripts, meetingTitle);

  await invoke('save_transcript', { filePath, content });
}